//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_order
    {
        public int id { get; set; }
        public Nullable<int> Order_status_id { get; set; }
        public Nullable<bool> Payed { get; set; }
        public Nullable<bool> Sended { get; set; }
        public Nullable<System.DateTime> Order_date { get; set; }
        public Nullable<System.DateTime> Sended_date { get; set; }
        public Nullable<int> Address_id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string User_id { get; set; }
        public Nullable<int> Products_to_order_id { get; set; }
        public decimal Total_price { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Order_status Order_status { get; set; }
        public virtual Products_to_order Products_to_order { get; set; }
    }
}
