//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_to_order
    {
        public int id_Products_to_order { get; set; }
        public int Products_order_id { get; set; }
        public Nullable<int> Product_id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Products_order Products_order { get; set; }
    }
}
