//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopDBEntities : DbContext
    {
        public ShopDBEntities()
            : base("name=ShopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Avalibility> Avalibility { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Order_status> Order_status { get; set; }
        public virtual DbSet<Producent> Producent { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Products_order> Products_order { get; set; }
        public virtual DbSet<Products_to_order> Products_to_order { get; set; }
    }
}
